version: '3.3'
services:
  cloudboard:
    image: cloudboard
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    entrypoint: yarn dev
    working_dir: /app