version: '3.3'
services:
  cloudboard:
    image: cloudboard-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app