version: '3'
services:
  cloudboard:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    entrypoint: yarn dev
    working_dir: /app
    user: "1000:1000"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    links:
      - cloudboard
    environment:
      - POSTGRES_PASSWORD=cloudboard_db_password
      - POSTGRES_USER=cloudboard_db_user
      - POSTGRES_DB=cloudboard_db